export const FEATURES = [
  'Scores', 'Video Streaming', 'Audio Streaming', 'Live Activities', 'Gameday/Gamecast',
  'Real Time Highlights', 'Special Events\n(HRD, ASG, Postseason)', 'Video On Demand', 'Basic Stats', 'Advanced Stats',
  'Player Info (Stats)', 'Standings', 'Schedule', 'News', 'Prospect Content',
  'Favorite Team', 'Follow Players', 'Follow Teams', 'Podcasts', 'Gaming (FTP)', 'Betting',
  'Club Information', 'Game Notifications', 'Social Content', 'Search', 'Vertical Video Explore',
  'Fan Content (Community)', 'Japanese Support'
];

export const APPS = [
  'MLB', 'ESPN', 'theScore', 'Real Sports', 'The Athletic', 'Apple Sports'
];

export const sampleData = [
  {
    app: 'MLB',
    Scores: 'Great',
    'Video Streaming': 'Great',
    'Audio Streaming': 'Great',
    'Live Activities': 'Good',
    'Gameday/Gamecast': 'Great',
    'Real Time Highlights': 'Great',
    'Special Events\n(HRD, ASG, Postseason)': 'Great',
    'Video On Demand': 'Great',
    'Basic Stats': 'Great',
    'Advanced Stats': 'Great',
    'Player Info (Stats)': 'Great',
    'Standings': 'Great',
    'Schedule': 'Great',
    'News': 'Good',
    'Prospect Content': 'Great',
    'Favorite Team': 'Great',
    'Follow Players': 'Great',
    'Follow Teams': 'Good',
    'Podcasts': 'Bad',
    'Gaming (FTP)': 'Good',
    'Betting': 'Bad',
    'Club Information': 'Great',
    'Game Notifications': 'Good',
    'Player Notifications': 'Good',
    'News Notifications': 'Great',
    'Social Content': 'Bad',
    'Search': 'Bad',
    'Vertical Video Explore': 'Bad',
    'Fan Content (Community)': 'Bad',
    'Japanese Support': 'Great'
  },
  {
    app: 'ESPN',
    Scores: 'Great',
    'Video Streaming': 'Bad',
    'Audio Streaming': 'Bad',
    'Live Activities': 'Great',
    'Gameday/Gamecast': 'Good',
    'Real Time Highlights': 'Bad',
    'Special Events\n(HRD, ASG, Postseason)': 'Good',
    'Video On Demand': 'Good',
    'Basic Stats': 'Great',
    'Advanced Stats': 'Bad',
    'Player Info (Stats)': 'Great',
    'Standings': 'Great',
    'Schedule': 'Great',
    'News': 'Good',
    'Prospect Content': 'Bad',
    'Favorite Team': 'Great',
    'Follow Players': 'Good',
    'Follow Teams': 'Good',
    'Podcasts': 'Good',
    'Gaming (FTP)': 'Bad',
    'Betting': 'Great',
    'Club Information': 'Good',
    'Game Notifications': 'Good',
    'Player Notifications': 'Bad',
    'News Notifications': 'Great',
    'Social Content': 'Bad',
    'Search': 'Good',
    'Vertical Video Explore': 'Good',
    'Fan Content (Community)': 'Bad',
    'Japanese Support': 'Good'
  },
  {
    app: 'theScore',
    Scores: 'Great',
    'Video Streaming': 'Bad',
    'Audio Streaming': 'Bad',
    'Live Activities': 'Good',
    'Gameday/Gamecast': 'Good',
    'Real Time Highlights': 'Bad',
    'Special Events\n(HRD, ASG, Postseason)': 'Good',
    'Video On Demand': 'Good',
    'Basic Stats': 'Good',
    'Advanced Stats': 'Bad',
    'Player Info (Stats)': 'Great',
    'Standings': 'Great',
    'Schedule': 'Great',
    'News': 'Good',
    'Prospect Content': 'Bad',
    'Favorite Team': 'Great',
    'Follow Players': 'Great',
    'Follow Teams': 'Great',
    'Podcasts': 'Bad',
    'Gaming (FTP)': 'Bad',
    'Betting': 'Good',
    'Club Information': 'Good',
    'Game Notifications': 'Great',
    'Player Notifications': 'Great',
    'News Notifications': 'Great',
    'Social Content': 'Good',
    'Search': 'Good',
    'Vertical Video Explore': 'Bad',
    'Fan Content (Community)': 'Good',
    'Japanese Support': 'Good'
  },
  {
    app: 'Real Sports',
    Scores: 'Great',
    'Video Streaming': 'Bad',
    'Audio Streaming': 'Bad',
    'Live Activities': 'Bad',
    'Gameday/Gamecast': 'Good',
    'Real Time Highlights': 'Bad',
    'Special Events\n(HRD, ASG, Postseason)': 'Bad',
    'Video On Demand': 'Good',
    'Basic Stats': 'Good',
    'Advanced Stats': 'Bad',
    'Player Info (Stats)': 'Great',
    'Standings': 'Good',
    'Schedule': 'Great',
    'News': 'Bad',
    'Prospect Content': 'Bad',
    'Favorite Team': 'Good',
    'Follow Players': 'Good',
    'Follow Teams': 'Good',
    'Podcasts': 'Bad',
    'Gaming (FTP)': 'Good',
    'Betting': 'Bad',
    'Club Information': 'Good',
    'Game Notifications': 'Great',
    'Player Notifications': 'Great',
    'News Notifications': 'Bad',
    'Social Content': 'Good',
    'Search': 'Good',
    'Vertical Video Explore': 'Good',
    'Fan Content (Community)': 'Good',
    'Japanese Support': 'Good'
  },
  {
    app: 'The Athletic',
    Scores: 'Great',
    'Video Streaming': 'Bad',
    'Audio Streaming': 'Bad',
    'Live Activities': 'Bad',
    'Gameday/Gamecast': 'Good',
    'Real Time Highlights': 'Bad',
    'Special Events\n(HRD, ASG, Postseason)': 'Bad',
    'Video On Demand': 'Bad',
    'Basic Stats': 'Bad',
    'Advanced Stats': 'Bad',
    'Player Info (Stats)': 'Good',
    'Standings': 'Great',
    'Schedule': 'Great',
    'News': 'Great',
    'Prospect Content': 'Bad',
    'Favorite Team': 'Great',
    'Follow Players': 'Bad',
    'Follow Teams': 'Bad',
    'Podcasts': 'Great',
    'Gaming (FTP)': 'Bad',
    'Betting': 'Good',
    'Club Information': 'Great',
    'Game Notifications': 'Good',
    'Player Notifications': 'Bad',
    'News Notifications': 'Great',
    'Social Content': 'Bad',
    'Search': 'Good',
    'Vertical Video Explore': 'Bad',
    'Fan Content (Community)': 'Bad',
    'Japanese Support': 'Bad'
  },
  {
    app: 'Apple Sports',
    Scores: 'Great',
    'Video Streaming': 'Bad',
    'Audio Streaming': 'Bad',
    'Live Activities': 'Great',
    'Gameday/Gamecast': 'Bad',
    'Real Time Highlights': 'Bad',
    'Special Events\n(HRD, ASG, Postseason)': 'Bad',
    'Video On Demand': 'Bad',
    'Basic Stats': 'Bad',
    'Advanced Stats': 'Bad',
    'Player Info (Stats)': 'Bad',
    'Standings': 'Good',
    'Schedule': 'Bad',
    'News': 'Bad',
    'Prospect Content': 'Bad',
    'Favorite Team': 'Great',
    'Follow Players': 'Bad',
    'Follow Teams': 'Bad',
    'Podcasts': 'Bad',
    'Gaming (FTP)': 'Bad',
    'Betting': 'Bad',
    'Club Information': 'Bad',
    'Game Notifications': 'Bad',
    'Player Notifications': 'Bad',
    'News Notifications': 'Bad',
    'Social Content': 'Bad',
    'Search': 'Bad',
    'Vertical Video Explore': 'Bad',
    'Fan Content (Community)': 'Bad',
    'Japanese Support': 'Bad'
  }
];

export const LABELS = ['Bad','Good','Great'];
export const SCORE_MAP = { Bad: 0, Good: 1, Great: 2 };